-- AlterTable
ALTER TABLE "Order" ADD COLUMN "taxAmount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN "taxRate" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "ShopSettings" ADD COLUMN "defaultTaxRate" INTEGER NOT NULL DEFAULT 0;
